"""add cloudinary fields to documents

Revision ID: 3b94776d5219
Revises: d90beb9db081
Create Date: 2026-06-14 09:19:42.492201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b94776d5219'
down_revision: Union[str, Sequence[str], None] = 'd90beb9db081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('cloudinary_url', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('cloudinary_public_id', sa.String(), nullable=True))
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'cloudinary_public_id')
    op.drop_column('documents', 'cloudinary_url')
    # ### end Alembic commands ###
